github:
  username: "your_github_username"
  token: "your_github_token"
  poll_interval: 300  # 检查间隔(秒)
  max_events: 3  # 最大推送数量


logging:
  level: INFO
  file: github_monitor.log

database:
  path: github_events.db

notifications:
  dingtalk:
    enable: true
    bots:
      - name: "主机器人"
        webhook: "https://oapi.dingtalk.com/robot/send?access_token=YOUR_TOKEN1"
        secret: "YOUR_SECRET1"
      - name: "备用机器人"
        webhook: "https://oapi.dingtalk.com/robot/send?access_token=YOUR_TOKEN2"
        secret: "YOUR_SECRET2"

  feishu:
    enable: true
    bots:
      - name: "主机器人"
        webhook: "https://open.feishu.cn/open-apis/bot/v2/hook/YOUR_TOKEN1"
        secret: "YOUR_SECRET1"
      - name: "备用机器人"
        webhook: "https://open.feishu.cn/open-apis/bot/v2/hook/YOUR_TOKEN2"
        secret: "YOUR_SECRET2"